In [64]:
from numpy import exp, array, random, dot, tanh 

In [84]:
#Red neuronal con una capa y función de activación tanh
class NeuralNetwork(): 
      
    def __init__(self): 
          
        # Using seed to make sure it'll   
        # generate same weights in every run 
        random.seed(1) 
          
        # 3x1 Weight matrix 
        self.weight_matrix = 2 * random.random((3, 1)) - 1
  
    # tanh as activation fucntion 
    def sigmoid(self,X):
        return 1/(1+np.exp(-X))

  
    # derivative of tanh function. 
    # Needed to calculate the gradients. 
    def sigmoid_derivative(self, x): 
        return 1 / (1 + exp(-x)) * (1 - (1 / (1 + exp(-x))))

  
    # forward propagation 
    #producto punto dentro de la función tangente entre las x y los pesos
    def forward_propagation(self, inputs): 
        return self.sigmoid(dot(inputs, self.weight_matrix)) 
      
    # training the neural network. 
    def train(self, train_inputs, train_outputs, 
                            num_train_iterations): 
                                  
        # Number of iterations we want to 
        # perform for this set of input. 
        for iteration in range(num_train_iterations): 
            output = self.forward_propagation(train_inputs) 
  
            # Calculate the error in the output. 
            #Diferencia entre lo calculado por la red y el real del data set
            error = train_outputs - output 
  
            # multiply the error by input and then  
            # by gradient of tanh funtion to calculate 
            # the adjustment needs to be made in weights 
            adjustment = dot(train_inputs.T, error *
                             self.sigmoid_derivative(output)) 
                               
            # Adjust the weight matrix 
            self.weight_matrix += adjustment 
  

In [77]:
#ejemplo con datos generados
#Notas: las X's se programan en forma de matriz nxm
#los outputs (y's) son un vector traspuesto, es decir vector vertical
#yo le puedo poner un pandas dataframe convertido en matriz
if __name__ == "__main__": 
      
    neural_network = NeuralNetwork() 
      
    print ('Random weights at the start of training') 
    print (neural_network.weight_matrix) 
  
    train_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]]) 
    train_outputs = array([[0, 1, 1, 0]]).T 
  
    neural_network.train(train_inputs, train_outputs, 10000) 
  
    print ('New weights after training') 
    print (neural_network.weight_matrix) 
  
    # Test the neural network with a new situation. 
    print ("Testing network on new examples ->") 
    print (neural_network.forward_propagation(array([1, 0, 0]))) 

Random weights at the start of training
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
New weights after training
[[15.03841089]
 [-0.40582887]
 [-7.23346225]]
Testing network on new examples ->
[0.99999971]


In [78]:
#ejemplo con data frame de ayer
import pandas as pd
train = pd.read_csv("droop_filenames.csv")

In [5]:
train.head()

droop                        filename   x0   y0   x1   y1   x2   y2   x3  \
0      0  keypoints/nodroop/nodroop1.jpg  182  180  187  199  192  217  199   
1      0  keypoints/nodroop/nodroop2.jpg  245  137  247  150  251  164  256   
2      0  keypoints/nodroop/nodroop3.jpg  111  192  114  220  120  246  125   
3      0  keypoints/nodroop/nodroop4.jpg  126  212  127  238  131  265  136   
4      0  keypoints/nodroop/nodroop5.jpg  131  204  129  227  132  252  135   

    y3  ...  x63  y63  x64  y64  x65  y65  x66  y66  x67  y67  
0  235  ...  267  235  288  230  268  236  259  238  251  238  
1  177  ...  307  181  322  177  308  181  301  183  294  183  
2  272  ...  230  282  258  289  230  297  214  297  200  295  
3  292  ...  229  299  257  303  229  299  217  300  205  299  
4  278  ...  231  294  260  295  231  292  220  293  209  291  

[5 rows x 138 columns]

In [104]:
#convierto en matriz mis x's
import numpy as np
traindata = np.asmatrix(train.loc[:,'x0':])
traindata.shape

(297, 136)

In [98]:
traindata


matrix([['keypoints/nodroop/nodroop1.jpg', 182, 180, ..., 238, 251, 238],
        ['keypoints/nodroop/nodroop2.jpg', 245, 137, ..., 183, 294, 183],
        ['keypoints/nodroop/nodroop3.jpg', 111, 192, ..., 297, 200, 295],
        ...,
        ['keypoints/droop/droop188.jpg', 85, 323, ..., 495, 246, 495],
        ['keypoints/droop/droop189.jpg', 149, 154, ..., 262, 242, 260],
        ['keypoints/droop/droop190.jpg', 24, 338, ..., 495, 229, 493]],
       dtype=object)

In [99]:
label = train['droop'].to_numpy()

In [100]:
label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int6

In [101]:
#convierto en vector vertical mis y's
train_outputs = label.T 
train_outputs

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int6

In [102]:
train_outputs.shape


(297,)

In [103]:
if __name__ == "__main__": 
      
    neural_network = NeuralNetwork() 
      
    print ('Random weights at the start of training') 
    print (neural_network.weight_matrix) 
  
    train_inputs = np.asmatrix(train.loc[:,'x0'])
    # train_inputs = np.asmatrix(train.loc[:,'filename':])
    print(train_inputs)
    train_outputs = label.T  
    print(train_outputs)
  
    neural_network.train(train_inputs, train_outputs, 1) 
  
    print ('New weights after training') 
    print (neural_network.weight_matrix) 
  


Random weights at the start of training
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
[[182 245 111 126 131 126 130 144  96 146 143 117 139 118 172 111 112 137
  132 115 124 149 132 195 139 136 213 151  94 110 107 110 151 138 123 166
  161 142 187 140 146 154 132 157  44 138  60 175  62 123 143 162 160 198
  148 223 255 234 101 174 128 133 180 143 143 163 158 136 132 172 170 148
  119 124  92 108  97 131 157  98 108 138 191 163 141 137 136 136 158 157
  151 141 270 239 176 126 137 168 141 142 114 126 122 123 157 118 138 120
  114 130 114 138 116 118 139  49 146 119 -26 -12 119 117  52  52  43 102
  103 181  62  16  69  86 101 121 156 178 131 109 125  99 129 140 132 166
  126 176 152  57  37  45  78  24  64 155 155 122  57  53 175 137 129 140
   54  75 140  91 214 110  59 104 115 116  99  55  33  46  37 113  73  38
   79  70  14  82  62  65  70  83  43  42  48  60  86  25  56  43  43  57
   81 407  52  87  63  87  46  70  27  33  57 120  87  19  85  99  99  85
   91  -3  94  88  34  75 

ValueError: shapes (1,297) and (3,1) not aligned: 297 (dim 1) != 3 (dim 0)

In [92]:
#probamos la red en el data set de test
test  = pd.read_csv("droop_filenames.csv")
testdata = np.asmatrix(test)

In [93]:
    # Test the neural network with a new situation. 
    print ("Testing network on new examples ->") 
    print (neural_network.forward_propagation(testdata) )

Testing network on new examples ->


ValueError: shapes (297,138) and (3,1) not aligned: 138 (dim 1) != 3 (dim 0)